# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Agent.BuildDirectory)' 
    contents: '**\OrderManager\bin\$(buildConfiguration)\netstandard2.0\bin\**' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)' 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/OrderManager-$(Build.BuildNumber).zip' 
    replaceExistingArchive: true 
  displayName: 'creating zip package $(Build.BuildNumber).zip'
